### PR TITLE
ENH: Add -d/--developer option to qSlicerCommandOptions

### PR DESCRIPTION
**Pull request by matthieuheitz**
This allows VesselView to launch in developer mode.

### CODE REVIEW

**Comment by matthieuheitz** [comment]
@jcfr can you review please ?

**Comment by matthieuheitz** [comment]
@vovythevov, can we change the name to `enable-developer-features` ?

**Comment by johan-andruejol** [comment]
Sure, it's not set in stone. There is no need to ask me things like this
though.

On Saturday, February 7, 2015, Matthieu Heitz notifications@github.com
wrote:

> @vovythevov https://github.com/vovythevov, can we change the name to
> enable-developer-features ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KitwareMedical/Slicer/pull/1#issuecomment-73240181.

## 

Sent from Gmail Mobile

**Comment by matthieuheitz** [comment]
Updated

**Comment by matthieuheitz** [comment]
Don't merge yet.

**Comment by jcfr** [comment]
[LGTM](http://www.lgtm.in/i/CrwlqWm7q)

[:+1:](http://www.lgtm.in/u/CrwlqWm7q) [:-1:](http://www.lgtm.in/r/CrwlqWm7q)

**Comment by jcfr** [comment]
@matthieuheitz Feel free to integrate this PR. In case you can't merge let me know and I will do it

**Comment by matthieuheitz** [comment]
Thank you ! It's okay, I can merge it.

**Pull request merged**
